/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplications"];
        put?: never;
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete: operations["unregisterApplication"];
        options?: never;
        head?: never;
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/applications/{application}:start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:register": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rebuildApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:purge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purgeApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get: operations["getConfiguration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateConfiguration"];
        trace?: never;
    };
    "/operations/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{operation}:watch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        get: operations["watchOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:tailLogs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get: operations["tailLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OperationReference: {
            name: string;
        };
        OperationResource: {
            name: string;
            /** @enum {string} */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            errorMessage?: string;
        };
        Application: {
            name: string;
            subdomain: string;
            repositoryUrl: string;
            ref: string;
            desiredState: string;
            observedState: string;
            /** @enum {string} */
            registrationState: "ACTIVE" | "UNREGISTERED";
            /** Format: date-time */
            observedAt: string;
            reconciling: boolean;
            latestOperation?: string;
            etag: string;
        };
        ApplicationList: {
            applications: components["schemas"]["Application"][];
        };
        ConfigurationResponse: {
            variables: {
                name: string;
                isSecret: boolean;
            }[];
        };
        CreateApplicationRequest: {
            /** Format: uri */
            repositoryUrl: string;
            ref: string;
            subdomain: string;
            /** Format: uuid */
            requestId: string;
        };
        UpdateApplicationRequest: {
            ref?: string;
            subdomain?: string;
            /** Format: uuid */
            requestId: string;
        };
        ConfigurationRequest: {
            variables: {
                [key: string]: components["schemas"]["Variable"];
            };
            /** Format: uuid */
            requestId: string;
        };
        ActionRequest: {
            /** Format: uuid */
            requestId: string;
        };
        PurgeRequest: {
            /** Format: uuid */
            requestId: string;
            /** @constant */
            confirm: true;
        };
        Variable: {
            value: string;
            secret: boolean;
        };
        Error: {
            error: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 稼働中 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 利用可能 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 利用不可 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listApplications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アプリ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationList"];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アプリ取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description 未検出 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unregisterApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    startApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    registerApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    stopApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    syncApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    rebuildApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    purgeApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurgeRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    getConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 設定取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationResponse"];
                };
            };
            /** @description 未検出 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigurationRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResource"];
                };
            };
        };
    };
    watchOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    tailLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
