/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listResourcePools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-pools/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPoolDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplications"];
        put?: never;
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete: operations["unregisterApplication"];
        options?: never;
        head?: never;
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/applications/{application}:start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:register": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rebuildApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}:purge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purgeApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get: operations["getConfiguration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateConfiguration"];
        trace?: never;
    };
    "/operations/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{operation}:watch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        get: operations["watchOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}/logEntries": {
        parameters: {
            query: {
                view: "task" | "application" | "related";
                service?: string;
                startAt?: string;
                endAt?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get: operations["listLogEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application}/logEntries:watch": {
        parameters: {
            query: {
                view: "task" | "application" | "related";
                service?: string;
                after?: string;
            };
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        get: operations["watchLogEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OperationReference: {
            name: string;
        };
        OperationResource: {
            name: string;
            kind: string;
            /** @enum {string} */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            phase?: string;
            displayMessage?: string;
            errorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Application: {
            name: string;
            /** @enum {string} */
            composeFile?: "compose.yaml" | "compose.yml" | "docker-compose.yaml" | "docker-compose.yml";
            subdomain: string;
            repositoryUrl: string;
            ref: string;
            desiredState: string;
            observedState: string;
            /** @enum {string} */
            registrationState: "ACTIVE" | "CONFIGURING" | "UNREGISTERED";
            /** Format: date-time */
            observedAt: string;
            reconciling: boolean;
            latestOperation?: string;
            latestError?: string;
            etag: string;
        };
        ApplicationList: {
            applications: components["schemas"]["Application"][];
        };
        LogEntry: {
            id: string;
            cursor: string;
            /** Format: date-time */
            occurredAt: string;
            /** @enum {string} */
            level: "debug" | "info" | "warn" | "error";
            /** @enum {string} */
            component: "backend" | "caddy" | "coredns" | "dashboard" | "application";
            applicationId?: string;
            operationId?: string;
            service?: string;
            containerName?: string;
            message: string;
        };
        LogEntryList: {
            entries: components["schemas"]["LogEntry"][];
            nextCursor?: string;
            liveCursor: string;
        };
        ConfigurationResponse: {
            variables: {
                name: string;
                isSecret: boolean;
                configured: boolean;
                value?: string;
                defaultValue?: string;
                required: boolean;
                hasDefault: boolean;
            }[];
            volumes: {
                name: string;
            }[];
            network: {
                name: string;
                purpose: string;
            };
            devices: {
                service: string;
                sourceHint: string;
                targetPath: string;
                permissions: string;
                configured: boolean;
                deviceId?: string;
            }[];
            deviceAccess: {
                allowed: boolean;
                message: string;
            };
            ready: boolean;
        };
        CreateApplicationRequest: {
            /** Format: uri */
            repositoryUrl: string;
            ref: string;
            subdomain: string;
            /** @enum {string} */
            composeFile?: "compose.yaml" | "compose.yml" | "docker-compose.yaml" | "docker-compose.yml";
            /** Format: uuid */
            requestId: string;
        };
        UpdateApplicationRequest: {
            ref?: string;
            subdomain?: string;
            /** Format: uuid */
            requestId: string;
        };
        ConfigurationRequest: {
            variables: {
                [key: string]: components["schemas"]["Variable"];
            };
            deviceBindings?: {
                service: string;
                targetPath: string;
                deviceId: string;
            }[];
            /** Format: uuid */
            requestId: string;
        };
        ActionRequest: {
            /** Format: uuid */
            requestId: string;
        };
        PurgeRequest: {
            /** Format: uuid */
            requestId: string;
            /** @constant */
            confirm: true;
        };
        ResourcePools: {
            devices: components["schemas"]["PoolDevice"][];
            physicalDevices: components["schemas"]["PhysicalDeviceResource"][];
            volumes: components["schemas"]["PoolResource"][];
            networks: components["schemas"]["PoolResource"][];
        };
        PoolDevice: {
            id: string;
            name: string;
            stableId: string;
            currentPath: string;
            status: string;
            metadata: {
                [key: string]: string;
            };
        };
        PhysicalDeviceResource: {
            stableId: string;
            currentPath: string;
            name: string;
            /** @enum {string} */
            category: "user" | "system";
            metadata: {
                [key: string]: string;
            };
        };
        PoolResource: {
            name: string;
            application: string;
            applicationName: string;
            status: string;
            /** @enum {string} */
            kind?: "edge" | "compose";
        };
        CreatePoolDeviceRequest: {
            name: string;
            candidateStableId: string;
        };
        PoolDeviceReference: {
            id: string;
        };
        Variable: {
            value?: string;
            defaultValue?: string;
            secret: boolean;
            keep?: boolean;
        };
        Error: {
            error: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 稼働中 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 利用可能 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 利用不可 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listResourcePools: {
        parameters: {
            query?: {
                includeSystem?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LWSリソースプール */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcePools"];
                };
            };
        };
    };
    createPoolDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePoolDeviceRequest"];
            };
        };
        responses: {
            /** @description デバイス登録完了 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolDeviceReference"];
                };
            };
        };
    };
    listApplications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アプリ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationList"];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アプリ取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description 未検出 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unregisterApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    startApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    registerApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    stopApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    syncApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    rebuildApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    purgeApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurgeRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    getConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 設定取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationResponse"];
                };
            };
            /** @description 未検出 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigurationRequest"];
            };
        };
        responses: {
            /** @description Operationを作成 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResource"];
                };
            };
        };
    };
    watchOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    listLogEntries: {
        parameters: {
            query: {
                view: "task" | "application" | "related";
                service?: string;
                startAt?: string;
                endAt?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntryList"];
                };
            };
            /** @description 検索条件が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未検出 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    watchLogEntries: {
        parameters: {
            query: {
                view: "task" | "application" | "related";
                service?: string;
                after?: string;
            };
            header?: never;
            path: {
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description 検索条件が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未検出 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
